services:
  - type: web
    name: cnas-strategic-portal
    runtime: node
    buildCommand: npm run build
    startCommand: npm run start
    envVars:
      - key: NODE_VERSION
        value: "20"
      - key: NODE_ENV
        value: production
